### PR TITLE
MAINT: Add support for python 3.11 and drop support for 3.7

### PR DESCRIPTION
**Pull request by zoj613**
Cc @ricardoV94

### CODE REVIEW

**Review by ricardoV94 — COMMENTED** [review]
Why pin a specific version of numpy? Can it be a minimum?

**Comment by zoj613** [comment]
> Why pin a specific version of numpy? Can it be a minimum?

Which part are you referring to? There is a pinned version of numpy for building and one for development.
1. Its important to pin the version to the lowest numpy version supported by a particular version of python. This is strongly encouraged by the numpy/scipy dev teams as well. Also see: https://numpy.org/neps/nep-0029-deprecation_policy.html
2. Pinning the numpy development version to the version installable in all supported python version seems sensible to ensure consistent behavior.

**Comment by ricardoV94** [comment]
In the pyproject, aren't you forcing a specific numpy version when installing the package with python 3.11? Instead of just a minimum version?

The reason I am asking is that other libraries might have also specific numpy requirements, not just because they test with it but because they actually need it (eg numba) which could unnecessarily become incompatible with this one. 

Or am I missing something?

**Comment by ricardoV94** [comment]
Ah is it just for building the wheels?

**Comment by zoj613** [comment]
> Ah is it just for building the wheels?

Yes, thats only for building the wheels since as I mentioned in the 2 points above that it must be done with the lowest supported numpy version for that particular version of python. For normal installation the lines
```toml
requires-python = ">=3.8"
dependencies = ["numpy >= 1.19.0"]
```
Are the only ones that matter.

**Comment by ricardoV94** [comment]
Nice, apologies for the confusion.

**Comment by zoj613** [comment]
The tests pass, but it looks like codecov is broken all of sudden and wont upload the code coverage report.

**Pull request merged**
